### PR TITLE
[#555] Add option to commit offsets

### LINKED ISSUE #555: Allow SubscribableKafkaMessageSource option of manually commiting offsets
### Enhancement Description

Currently when using the consumer choice of SubscribableKafkaMessageSource, there is no way to commit offsets pragmatically. It depends on `enable-auto-commit: true` to be set.

The problem with this is when a batch of consumer records are processed (lets say a batch size of 50), the batch could fail on the 15th message AND in the background the consumer can commit offsets through to the 50th event.  When the consumer then resubscribes the events from 15 - 50 have been missed.

I'm proposing an option to allow FetchEventsTask to manually commit the offsets. 

### Current Behaviour

When an event throws an exception the consumer can commit the offsets and then miss records.  

### Wanted Behaviour

 Maybe after the processRecords(...) shown below, the offsets could be committed if auto commit is disabled.

```
@Override
public void run() {
    try {
        while (running.get()) {
            ConsumerRecords<K, V> records = consumer.poll(pollTimeout);
            logger.debug("Fetched [{}] number of ConsumerRecords", records.count());
            processRecords(records);
        }
    } catch (Exception e) {
        logger.warn("Encountered an exception fetching ConsumerRecords", e);
        runtimeErrorHandler.handle(new FetchEventException(
                "Cannot proceed with fetching ConsumerRecords since we encountered an exception",
                e));
    } finally {
        running.set(false);
        closeHandler.accept(this);
        consumer.close();
        logger.info("Fetch events task and used Consumer instance [{}] have been closed", consumer);
    }
}
```

### Possible Workarounds

I don't think a work-a-round is possible.

### PR DESCRIPTION
**Pull request by bradskuse**
Resolves #555 

This adds an option so that offsets can be committed after processing of events, instead of using enable auto commit.

Edit: Added ability to use auto, async or sync

### CODE REVIEW

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package org.axonframework.extensions.kafka.eventhandling.consumer;
+
+/**
+ * Enum to define how the consumer will handle committing offsets.
+ */
+public enum OffsetCommitType {
+    AUTO,
+    COMMIT_ASYNC,
+    COMMIT_SYNC
```
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java:9]: Nit: Each enumeration option should have some JavaDoc! Would you mind adding that, @bradskuse?

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java [hunk 2]
```diff
@@ -0,0 +1,10 @@
+package org.axonframework.extensions.kafka.eventhandling.consumer;
+
+/**
+ * Enum to define how the consumer will handle committing offsets.
```
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java:4]: Feel free to add an `@author` tag with your name, and an `@since` tag referring to 4.11.1 to the class-level JavaDoc! :-)

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package org.axonframework.extensions.kafka.eventhandling.consumer;
```
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/OffsetCommitType.java:1]: New files should have a copyright notice to state all is Apache 2 licensed. You can find the copyright notice template [here](https://github.com/AxonFramework/AxonFramework/blob/master/copyright-template.xml). Or, you can copy it from another file in this repository and adjust the date accordingly.

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java [hunk 4]
```diff
@@ -163,6 +167,21 @@ public Builder<K, V, E> pollTimeout(long timeoutMillis) {
...
+         * {@link OffsetCommitType#AUTO} let the Kafka consumer commit offsets automatically in background
+         * {@link OffsetCommitType#COMMIT_SYNC} let the Kafka consumer commit offsets synchronously after processing
+         * {@link OffsetCommitType#COMMIT_ASYNC} let the Kafka consumer commit offsets asynchronously after processing
+         * Defaults to {@code OffsetCommitType#AUTO}
+         *
+         * @param offsetCommitType {@link OffsetCommitType} enum to specify the offset commit type
+         * @return the current Builder instance, for fluent interfacing
+         */
+        public AsyncFetcher.Builder<K, V, E> offsetCommitType(OffsetCommitType offsetCommitType) {
+            this.offsetCommitType = offsetCommitType;
```
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java:181]: Nit: Please verify that the given `offsetCommitType` is not `null`. You can use the `assertNonNull` method from the `Builder#executorService` method, for that, for example.

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java [hunk 5]
```diff
@@ -163,6 +167,21 @@ public Builder<K, V, E> pollTimeout(long timeoutMillis) {
             return this;
         }
 
+        /**
+         * Set the {@code offsetCommitType}, options are:
+         * {@link OffsetCommitType#AUTO} let the Kafka consumer commit offsets automatically in background
+         * {@link OffsetCommitType#COMMIT_SYNC} let the Kafka consumer commit offsets synchronously after processing
+         * {@link OffsetCommitType#COMMIT_ASYNC} let the Kafka consumer commit offsets asynchronously after processing
+         * Defaults to {@code OffsetCommitType#AUTO}
```
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java:175]: Minor restructuring suggestion:
```suggestion
     * Sets the {@code offsetCommitType} defining how the {@link FetchEventsTask} will commit offsets during processing of events.
     *
     * Options are:
     * <ul>
     *     <li>{@link OffsetCommitType#AUTO} - let the Kafka consumer commit offsets automatically in background.</li>
     *     <li>{@link OffsetCommitType#COMMIT_SYNC} - let the Kafka consumer commit offsets synchronously after processing.</li>
     *     <li>{@link OffsetCommitType#COMMIT_ASYNC} - let the Kafka consumer commit offsets asynchronously after processing.</li>
     * </ul>
     *
     * Defaults to {@code OffsetCommitType#AUTO}, meaning the offset commit task happens in the background.
```

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcher.java:1]: Changes to this file should update the copyright notice to this year. More specifically, that means line 2 of this file should state the following:
```txt
Copyright (c) 2010-2025. Axon Framework
```

File: kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/FetchEventsTask.java
Comment (smcvb) [inline kafka/src/main/java/org/axonframework/extensions/kafka/eventhandling/consumer/FetchEventsTask.java:1]: Changes to this file should update the copyright notice to this year. More specifically, that means line 2 of this file should state the following:
```txt
Copyright (c) 2010-2025. Axon Framework
```

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/FetchEventsTaskTest.java
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/FetchEventsTaskTest.java:1]: Changes to this file should update the copyright notice to this year. More specifically, that means line 2 of this file should state the following:
```txt
Copyright (c) 2010-2025. Axon Framework
```

**Review by smcvb — CHANGES_REQUESTED** [review]
Conceptually I think there's nothing wrong with the changes. So, thanks for the effort there, @bradskuse! However, I do have some minor concerns we need to address. So, if you could take a look at those once you have found the time for that, that would be great.

**Comment by bradskuse** [comment]
Hey @smcvb 

Thank you for reviewing this PR.  I have just pushed up all the changes requested 👍

**Review by smcvb — APPROVED** [review]
My concerns have been addressed, hence I'm approving this pull request.
