### PR TITLE
#108 Migrate tests to junit5 and testcontainers

### LINKED ISSUE #108: Fix CI build and optimise test process
### Enhancement Description

Fix the CI build by either making test more resilient to random failures, or using another approach for integration testing. 
One different approach to integration testing might be to replace `EmbeddedKafka` with `TestContainers` Kafka module.

### Current Behaviour

Since moving to GitHub Actions, the CI build and tests are not very stable. While locally all tests are green, on GHA various random tests fail on each build. Occasionally `java.lang.OutOfMemoryError: Java heap space` or similar errors will occur which may indicate the root problem for other failing tests cases and explain why there are no failures locally. It seems that the test executing process can take more than 4GB of RAM at one point which can put a lot of memory pressure on the CI JVM.

### Wanted Behaviour

Consistent CI builds and passing tests

### PR DESCRIPTION
**Pull request by lfgcampos**
This PR has a lot of work around testing.

It migrates every test to junit5 and also introduce `@Testcontainers` approach instead of `EmbeddedKafka`.

Fixes #108.

### CODE REVIEW

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+ */
+public class KafkaContainerCluster implements Startable {
+
+    private final int brokersNum;
+    private final Network network;
+    private final GenericContainer<?> zookeeper;
+    private final Collection<KafkaContainer> brokers;
+
+    public KafkaContainerCluster(String confluentPlatformVersion, int brokersNum, int internalTopicsRf) {
+        if (brokersNum < 0) {
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:33]:
```suggestion
        if (brokersNum <= 0) {
```

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+            throw new IllegalArgumentException("brokersNum '" + brokersNum + "' must be greater than 0");
+        }
+        if (internalTopicsRf < 0 || internalTopicsRf > brokersNum) {
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:36]:
```suggestion
        if (internalTopicsRf <= 0 || internalTopicsRf > brokersNum) {
```

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+@Testcontainers
+public class KafkaContainerClusterTest {
+
+    @Container
+    protected static final KafkaContainerCluster KAFKA_CLUSTER = new KafkaContainerCluster("5.4.3",
+                                                                                           3,
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java:11]: Nit: Weird formatting

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+ * Test utility for Kafka admin operations.
+ *
+ * @author Stefan Andjelkovic
+ * @author Lucas Campos
+ */
+public class KafkaAdminUtils {
+
+    private static final Logger logger = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
+
+    public static void createTopics(String bootstrapServer, String... topics) {
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java:36]: Missing Javadocs on public methods. Applies for all public method in this class

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package org.axonframework.extensions.kafka.eventhandling.util;
+
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+@Testcontainers
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java:6]: Missing Javadoc

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java [hunk 6]
```diff
@@ -0,0 +1,15 @@
+package org.axonframework.extensions.kafka.eventhandling.util;
+
+import org.testcontainers.containers.KafkaContainer;
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+import org.testcontainers.utility.DockerImageName;
+
+@Testcontainers
+public abstract class KafkaContainerTest {
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java:9]: Missing Javadoc

File: kafka/pom.xml [hunk 7]
```diff
@@ -34,6 +34,7 @@
         <spring-kafka-test.version>2.6.5</spring-kafka-test.version>
```
Comment (sandjelkovic) [inline kafka/pom.xml:34]: Cleanup: `spring-kafka-test` dependency is not needed anymore

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcherTest.java [hunk 8]
```diff
@@ -63,20 +59,58 @@
...
 
-    @SuppressWarnings("SpringJavaAutowiredMembersInspection")
-    @Autowired
-    private EmbeddedKafkaBroker kafkaBroker;
-
     private AsyncFetcher<String, String, KafkaEventMessage> testSubject;
 
+    @BeforeAll
+    public static void before() {
+        KafkaAdminUtils.createTopics(KAFKA_CONTAINER.getBootstrapServers(), TEST_TOPIC);
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/consumer/AsyncFetcherTest.java:72]: Nit: `KAFKA_CONTAINER.getBootstrapServers()` can be moved to `KafkaContainerTest`as a base method that the tests can use without caring about the Container at all

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java [hunk 9]
```diff
@@ -0,0 +1,112 @@
...
+ * @author Lucas Campos
+ */
+
+public class DefaultProducerFactoryClusteringTest extends KafkaContainerClusterTest {
+
+    private static final String TOPIC = "testSendingMessagesUsingMultipleTransactionalProducers";
+
+    @BeforeAll
+    static void before() {
+        KafkaAdminUtils.createTopics(KAFKA_CLUSTER.getBootstrapServers(), TOPIC);
```
Comment (sandjelkovic) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java:35]: Nit: `KAFKA_CLUSTER.getBootstrapServers()` can be moved to `KafkaContainerClusterTest` as a base method that the tests can use without knowing about the Container or Cluster at all

**Review by sandjelkovic — COMMENTED** [review]
Minor things are left, like javadoc and cleanup. Otherwise looks great 👍

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 10]
```diff
@@ -0,0 +1,107 @@
...
+        );
+    }
+
+    @Override
+    public void start() {
+        Stream<Startable> startables = this.brokers.stream().map(Startable.class::cast);
+        try {
+            Startables.deepStart(startables).get(60, SECONDS);
+        } catch (InterruptedException | ExecutionException | TimeoutException e) {
+            e.printStackTrace();
```
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:90]: Is printing the stack trace sufficient? Shouldn't we throw the exception too, or log it? 
I'd assume the test set up should fail in absence of any of the desired containers.

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+        }
+        Unreliables.retryUntilTrue(30, TimeUnit.SECONDS, () -> {
```
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:92]: Curious: is this because ZooKeeper is unreliable during start-up? Or are you guys uncertain as this has been copied from a different location? ;-)

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java [hunk 12]
```diff
@@ -0,0 +1,18 @@
+package org.axonframework.extensions.kafka.eventhandling.util;
+
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+
+/**
+ * A cluster of kafkas using test container.
```
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerClusterTest.java:7]: I'd more so anticipate something like this:

```suggestion
 * A {@link KafkaContainerCluster} set up by using {@link Testcontainers.
```

And similarly, some author tags. Grab those creds :p

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java [hunk 13]
```diff
@@ -0,0 +1,22 @@
+package org.axonframework.extensions.kafka.eventhandling.util;
+
+import org.testcontainers.containers.KafkaContainer;
+import org.testcontainers.junit.jupiter.Container;
+import org.testcontainers.junit.jupiter.Testcontainers;
+import org.testcontainers.utility.DockerImageName;
+
+/**
+ * A single node of kafka using test container.
```
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerTest.java:9]: Same argumentation on this guy as I placed on the `KafkaContainerClusterTest` class.

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java [hunk 14]
```diff
@@ -0,0 +1,112 @@
...
+            producer.commitTransaction();
+            testProducers.add(producer);
+        });
+        assertOffsets(results);
+
+        cleanup(producerFactory, testProducers);
+    }
+
+    @Test
+//    @Disabled("clustering is needed")
```
Comment (smcvb) [inline kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/producer/DefaultProducerFactoryClusteringTest.java:98]: I think this comment can be removed.

**Review by smcvb — CHANGES_REQUESTED** [review]
Several relatively small arguments to go over prior to approval.

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 15]
```diff
@@ -0,0 +1,107 @@
...
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+import java.util.stream.Collectors;
+import java.util.stream.IntStream;
+import java.util.stream.Stream;
+
+import static java.util.concurrent.TimeUnit.SECONDS;
+
+/**
+ * Copied from https://github.com/testcontainers/testcontainers-java/blob/master/examples/kafka-cluster/src/test/java/com/example/kafkacluster/KafkaContainerCluster.java
```
[the remark this answers is not in the document]
Comment (lfgcampos) [reply kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:23]: I haven't made any adjustment so far and there is no author on the original class.

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java [hunk 16]
```diff
@@ -0,0 +1,140 @@
...
+        try (AdminClient adminClient = AdminClient.create(minimalAdminConfig(bootstrapServer))) {
+            CreateTopicsResult topicsCreationResult = adminClient.createTopics(topics(topics));
+            topicsCreationResult.values().values()
+                                .forEach(KafkaAdminUtils::waitForCompletion);
+            logger.info("Completed topic creation");
+        }
+    }
+
+    /**
+     * Method responsible for creating partitions on given kafka and topics.
```
[the remark this answers is not in the document]
Comment (lfgcampos) [reply kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaAdminUtils.java:52]: Changed slightly different, also including `@code` for the `bootstrapServer` variable.

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (smcvb) [reply kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java]: That definitely complicates things. Isn't the original commiter in the commit messages of the class you guys copied?

File: kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/SubscribingProducerIntegrationTest.java [hunk 17]
```diff
@@ -47,7 +47,7 @@ public void shouldPublishMessagesSynchronously() throws Exception {
         eventBus.publish(new GenericEventMessage<>("test"));
 
         // then
-        assertThat(Thread.currentThread().getId()).isEqualTo(threadIdCaptor.getThreadId());
```
Comment (smcvb) [inline kafka-spring-boot-autoconfigure/src/test/java/org/axonframework/extensions/kafka/SubscribingProducerIntegrationTest.java:50]: I believe we can remove the `public` modifier from this method and from the test class. Or is this not an option because it's a `@SpringBootTest`?

File: kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java [hunk 18]
```diff
@@ -0,0 +1,107 @@
...
+ * Should be an utility class to help set up a cluster of kafkas using test container approach.
+ */
+public class KafkaContainerCluster implements Startable {
+
+    private final int brokersNum;
+    private final Network network;
+    private final GenericContainer<?> zookeeper;
```
[the remark this answers is not in the document]
Comment (smcvb) [reply kafka/src/test/java/org/axonframework/extensions/kafka/eventhandling/util/KafkaContainerCluster.java:32]: Issue resolved through video chat - this approach is taken as it's a copied version from test containers themselves.

**Review by smcvb — APPROVED** [review]
My concerns have been addressed, hence approving.
